from typing import TypedDict, List, Annotated
from models.job import Job
import operator

class AgentState(TypedDict):
    """
    Represents the state of our job search agent. This is the single source
    of truth for the agent's memory structure.
    """
    # Inputs from the user
    resume_text: str
    search_prompt: str
    
    # State generated by the agent
    search_queries: List[str]
    
    # List of urls to process
    urls_to_process: List[str] 
    
    # Running list of extracted jobs
    extracted_jobs: Annotated[List[Job], operator.add]
    
    # State for the processing loop
    url_index: int
    current_url: str
    current_page_text: str
    current_page_classification: str
    
    # This key is set by the final node, but we define it here for completeness.
    final_jobs: List[Job]
